# Sử dụng một ảnh gốc có sẵn chứa Node.js
FROM node:18.12.1-alpine
# Tạo thư mục ứng dụng trong container
WORKDIR /app

# Sao chép tệp package.json vào thư mục ứng dụng
COPY package.json ./

# Cài đặt các phụ thuộc
RUN npm install

# Sao chép mã nguồn ứng dụng vào thư mục ứng dụng
COPY . .

# Xây dựng ứng dụng React
RUN npm run build

# Khởi chạy ứng dụng khi container được chạy
CMD ["npm", "start"]

